export enum PERMISSIONS { // 购买会员的方式
  ALL_ADMIN = 100, // 所有角色拥有
  USER_ADD = 101, // 用户线索新建
  USER_DIS = 102, // 用户线索分配
  USER_SEARCH = 103, // 用户线索查询
  USER_EDIT = 104, // 用户线索编辑
  USER_LIST_SEARCH_ALL = 105, // 用户线索列表查询（全部）
  USER_LIST_SEARCH_PART = 106, // 用户线索列表查询（部分）
  USER_CLUES_CIRCULATION = 108, // 线索流转权限（超管、C端运营、咨询师）
  USER_CLUES_DOWNLOAD = 110, // 用户线索下载权限
  USER_INFO_UNRESOLVED = 10000, // 线索清洗权限
  DISPATCH_TASK = 201, // 线索派单
  DISPATCH_TASK_LIST_QUERY_ALL = 202, // 派单列表查询（全部）
  DISPATCH_TASK_LIST_QUERY_PART = 203, // 派单列表查询（部分）
  DISPATCH_TASK_FOLLOW_B = 204, // 线索跟进 for B
  DISPATCH_TASK_FOLLOW_C = 205, // 线索跟进 for C
  DISPATCH_TASK_SUPPLEMENT = 208, // 查看补单信息的权限(用户运营，超管，机构运营，机构运营管理有该权限)
  DATA_STATISTICS_CONVERT = 301, // 派单转化数据查看
  DATA_STATISTICS_HOSPITAL = 302, // 派单机构数据查看
  DATA_STATISTICS_CONSULTANTS = 303, // 咨询师数据查看
  DATA_STATISTICS_NETWORK_CONSULTANTS = 304, // 网络咨询数据查看
  DATA_STATISTICS_USERS = 305, // 用户来源数据查看
  DATA_STATISTICS_ALL = 306, // 总体数据查看
  DATA_DOWNLOAD_STATISTICS = 401, // 统计数据下载
  DATA_DOWNLOAD_DISPATCH = 402, // 派单明细下载
  SYS_ADMIN = 500, // 系统管理员权限
  SYS_USER_CREATE = 501, // 系统用户新建
  SYS_USER_QUERY = 502, // 系统用户查询
  SYS_USER_UPDATE = 503, // 系统用户编辑
  SYS_USER_DELETE = 504, // 系统用户删除
  SYS_USER_LIST_QUERY_ALL = 505, // 系统用户列表查询
  SYS_USER_ADMIN = 506, // 咨询师网咨SysUser操作权限（C端运营）
  SYS_USER_GROUP = 508, // 分组管理操作权限（超管、C端运营）
  SYS_USER_GET_BY_ROLE = 509, // 分组根据角色查询系统用户权限
  TASK_MANAGE_ADMIN = 600, // 任务管理权限（咨询师、机构运营、机构运营管理、超管）
  TASK_MANAGE_HEAD = 601, // 任务负责人（机构运营-组长、用户运营、机构运营管理、超级管理员）
  TASK_ACTUAL_STATE = 602, // 任务实际状态（超级管理员、机构运营管理、用户运营）
  TASK_DETAILS_DOWNLOAD = 603, // 任务明细下载（用户运营、机构运营管理、超级管理员）
  TASK_MANAGE_DISPATCH = 604, // 任务改派 （机构运营管理、机构运营-组长）
  SYS_USER_ORGAN_OPERATE = 510, // 机构运营SysUser操作权限
  SYS_USER_GROUP_ORGAN_OPERATE = 512, // 分组管理操作权限(机构运营管理)
  SYS_USER_INITIATE_REPLENISHMENT = 207, // 机构运营，超管，机构运营具有的权限
  CHANNEL_SOURCE_MANAGEMENT_READ = 150, // 渠道来源管理查看（用户运营、数据管理、超管）
  CHANNEL_SOURCE_MANAGEMENT_WRITE = 151, // 渠道来源管理编辑（用户运营、超管）
  PERMISSION_MANAGE = 309, // 绩效管理（超管、用户运营、咨询师、网咨）
  KNOWLEDGE_EDITOR = 700, // 知识库的编辑权限
  ALL = 0, // 所有用户
}
